---
# Hostname. Used to determine the FQDN, for server settings, and in Django's settings file
# Django will disallow any HTTP requests not sent to this domain name ("localhost" is also allowed for convenience)
# this hostname is also used for OIDC return, so it must be set to what your browser actually displays in the title bar.
hostname: "test.example.com"
# Institution name. This will render in templates and settings in various places.
institution_name: Example Institution

# Administrator name and email
administrator:
  name: "Local Administrator Full Name"
  email: "administrator@example.com"

# Project-specific settings
project:
  name: "My Project's Data Transfer Portal"
  description: "A Site to Initiate Globus Data Transfers for My Project"
  sub_description: "This is a demonstration project with default settings"
  version: "0.1.0"

# Globus settings. To determine these, See README.md
globus:
  client_id: 1234567-1234-1234-1234-123456789012
  secret_key: akldichfj8e9vnowinuNEFFEJ0
  search_index: 1234567-1234-1234-1234-123456789012
  collections:
    - id: 1234567-1234-1234-1234-123456789012
      name: Example collection 1
      description: This collection is included as an example.
    - id: 1234567-1234-1234-1234-123456789012
      name: Example collection 2
      description: This collection is included as an example.
    - id: 1234567-1234-1234-1234-123456789012
      name: Example collection 3
      description: This collection is included as an example.

# Styling data
colors:
  header: "#333333"
  primary: "#3E5C93"
  secondary: "#7777CC"
  white: "#FFFFFF"
  surfaces:
    - "#FFFFFF"
    - "#EEEEEE"
    - "#DDDDDD"

logos:
  primary: https://www.globus.org/assets/images/logo_globus-solid.svg
  secondary: https://www.globus.org/assets/images/logo_globus-solid.svg

customization:
  section: "Research Staff"
  teammates:
    - name: "Jane Doe"
      email: "jdoe@example.com"
      position: Research Scientist
    - name: "John Doe"
      email: "jdoe2@example.com"
      position: Research Scientist
    - name: "Jay Doe"
      email: "jdoe3@example.com"
      position: Research Scientist

# HTML templates (UI partials)
# these paths are relative to this ansible role.
# The files can be altered to give you as much control as possible
# over the layout of the site and its functionality.
templates:
  - name: Base template
    template: ../templates/base.html
    destination: /backend/templates/globus-portal-framework/v2/base.html
  - name: Logo File
    template: ../templates/identity/logo.png
    destination: /backend/static/
  - name: Header Block Template
    template: ../templates/header.html
    destination: /backend/templates/globus-portal-framework/v2/components/base-nav.html
  - name: Footer Block Template
    template: ../templates/footer.html
    destination: /backend/templates/globus-portal-framework/v2/components/footer.html
  - name: Main Page template
    template: ../templates/main.html
    destination: /backend/templates/globus-portal-framework/v2/landing-page.html
  - name: Transfer Page
    template: ../templates/transfers.html
    destination: /backend/templates/globus-portal-framework/v2/components/transfer/home.html
  - name: Getting Started Block Template
    template: ../templates/getting_started_block.html
    destination: /backend/templates/globus-portal-framework/v2/components/getting_started_block.html
  - name: Documentation Block
    template: ../templates/documentation_block.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation_block.html
  - name: Documentation Page
    template: ../templates/documentation.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation.html
  - name: Documentation Overview
    template: ../templates/documentation/overview.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation/overview.html
  - name: Documentation on Transfers
    template: ../templates/documentation/transfers.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation/overview.html
  - name: Customization Block Template
    template: ../templates/customization.html
    destination: /backend/templates/globus-portal-framework/v2/components/ 
  - name: Global Stylesheet
    template: ../templates/style.css
    destination: /backend/static/
  - name: Illustration
    template: ../templates/identity/illustration.svg
    destination: /backend/static/
    
static:
  - name: Logo File
    file: ../templates/identity/logo.png
    destination: /backend/static/
