---
# Hostname. Used to determine the FQDN, for server settings, and in Django's settings file
# Django will disallow any HTTP requests not sent to this domain name ("localhost" is also allowed for convenience)
# this hostname is also used for OIDC return, so it must be set to what your browser actually displays in the title bar.
hostname: "test.example.com"
# Institution name. This will render in templates and settings in various places.
institution_name: Example Institution

# Administrator name and email
administrator:
  name: "Local Administrator Full Name"
  email: "administrator@example.com"

# Project-specific settings
project:
  name: "Globus Data Transfer Hub"
  description: "The Globus Data Transfer Hub streamlines high-speed data transfers for your project. 
  This portal allows you to initiate secure, reliable  file transfers between authorized Globus source/destination points,
  browse datasets for transfers and monitor transfer progress. The Globus Data Transfer Hub accelerates research 
  workflows and enhancing collaboration by providing a centralized access point to facilitate data movement."
  version: "0.1.0"

# Globus settings. To determine these, See README.md
globus:
  client_id: null
  secret_key: null
  search_index: null
  collections:
    - id: null
      name: Example collection
      description: This collection is included as an example.
    - id: null
      name: Example collection
      description: This collection is included as an example.
    - id: null
      name: Example collection
      description: This collection is included as an example.

# Styling data
colors:
  header: "#333333"
  primary: "#EAEBEF"
  secondary: "#49C5DC"
  white: "#FFFFFF"
  surfaces:
    - "#FFFFFF"
    - "#EEEEEE"
    - "#DDDDDD"

# Logo - All logo should be in the static directory
logo: "static/Fasterdata_Logo.svg"

# Customization - Add customizable content - further edit customization.html
customization:
  section: "Ex. Meet Our Teammates"
  teammates:
    - name: "John Doe"
      email: "manager@example.com"
      position: Manager
    - name: "John Doe"
      email: "manager@example.com"
      position: Manager
    - name: "John Doe"
      email: "manager@example.com"
      position: Manager


# HTML templates (UI partials)
# these paths are relative to this ansible role.
# The files can be altered to give you as much control as possible
# over the layout of the site and its functionality.
templates:
  - name: Base template
    template: ../templates/base.html
    destination: /backend/templates/globus-portal-framework/v2/base.html
  - name: Header Block Template
    template: ../templates/header.html
    destination: /backend/templates/globus-portal-framework/v2/components/base-nav.html
  - name: Footer Block Template
    template: ../templates/footer.html
    destination: /backend/templates/globus-portal-framework/v2/components/footer.html
  - name: Main Page template
    template: ../templates/main.html
    destination: /backend/templates/globus-portal-framework/v2/landing-page.html
  - name: Transfer Page
    template: ../templates/transfers.html
    destination: /backend/templates/globus-portal-framework/v2/components/transfer/home.html
  - name: Getting Started Block Template
    template: ../templates/getting_started_block.html
    destination: /backend/templates/globus-portal-framework/v2/components/getting_started_block.html
  - name: Documentation Block
    template: ../templates/documentation_block.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation_block.html
  - name: Documentation Page
    template: ../templates/documentation.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation.html
  - name: Documentation Overview
    template: ../templates/documentation/overview.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation/overview.html
  - name: Documentation on Transfers
    template: ../templates/documentation/transfers.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation/overview.html
  - name: Global Stylesheet
    template: ../templates/style.css
    destination: /backend/static/
  - name: Illustration
    template: ../templates/identity/illustration.svg
    destination: /backend/static/
  - name: Pin File
    template: ../templates/identity/pin.svg
    destination: /backend/static/
  - name: Customization Block Template
    template: ../templates/customization.html
    destination: /backend/templates/globus-portal-framework/v2/components/ 

static: 
  - name: Logo File
    template: ../templates/identity/Fasterdata_Logo.svg
    destination: /backend/static/
  - name: Transfer Page Image
    template: ../templates/identity/transferpage.jpg
    destination: /backend/static/  
  - name: Berkeley Lab Footer Badge
    template: ../templates/identity/Berkeley_Lab-footer-badge.png
    destination: /backend/static/ 
  - name: Transfer Page Image
    template: ../templates/identity/DOE_SC_footer-badge.png
    destination: /backend/static/   




