---
# Hostname. Used to determine the FQDN, for server settings, and in Django's settings file
# Django will disallow any HTTP requests not sent to this domain name ("localhost" is also allowed for convenience)
# this hostname is also used for OIDC return, so it must be set to what your browser actually displays in the title bar.
hostname: "mrdp.mooo.com"
# Institution name. This will render in templates and settings in various places.
institution_name: ESnet Data Portal

# Administrator name and email
administrator:
  name: "Local Administrator Full Name"
  email: "jkafader@es.net"

# Project-specific settings
project:
  name: "Globus Data Transfer Hub"
  description: "The Globus Data Transfer Hub streamlines high-speed data transfers for your project."
  sub_description: "A centralized access point to facilitate data movement, accelerating research workflows and enhancing collaboration."

  version: "0.1.0"

# Globus settings. To determine these, See README.md
# Globus settings. To determine these, See README.md
globus:
  client_id: N/A
  secret_key:  N/A
  search_index:  N/A
  collections:
    - id:  N/A
      name: ESnet Read-Only Test DTN at Washington
      description: Anonymous read-only Globus test host in Washington, DC
    - id:  N/A
      name: ESnet Read-Only Test DTN at Starlight in Chicago
      description: Anonymous read-only Globus test host at Starlight Chicago
    - id:  N/A
      name: ESnet Read-Only Test DTN in Sunnyvale
      description: Anonymous read-only Globus test host in Sunnyvale, CA

# Styling data
colors:
  header: "#343A40"
  primary: "#EAEBEF"
  secondary: "#62CAF5"
  white: "#FFFFFF"
  surfaces:
    - "#FFFFFF"
    - "#EEEEEE"
    - "#DDDDDD"

# Logo - All logo should be in the static directory
logo: "../../static/ESnet_Logo.png"
secondary_logo: "../../static/ESnet_Logo_Sphere.png"

# Customization - Add customizable content - further edit customization.html
customization:
  section: "Meet Our Team"
  teammates:
    - name: "John Doe"
      email: "manager@example.com"
      position: Manager
    - name: "John Doe"
      email: "manager@example.com"
      position: Manager
    - name: "John Doe"
      email: "manager@example.com"
      position: Manager


# HTML templates (UI partials)
# these paths are relative to this ansible role.
# The files can be altered to give you as much control as possible
# over the layout of the site and its functionality.
templates:
  - name: Base template
    template: ../templates/base.html
    destination: /backend/templates/globus-portal-framework/v2/base.html
  - name: Header Block Template
    template: ../templates/header.html
    destination: /backend/templates/globus-portal-framework/v2/components/base-nav.html
  - name: Footer Block Template
    template: ../templates/footer.html
    destination: /backend/templates/globus-portal-framework/v2/components/footer.html
  - name: Main Page template
    template: ../templates/main.html
    destination: /backend/templates/globus-portal-framework/v2/landing-page.html
  - name: Transfer Page
    template: ../templates/transfers.html
    destination: /backend/templates/globus-portal-framework/v2/components/transfer/list.html
  - name: Getting Started Block Template
    template: ../templates/getting_started_block.html
    destination: /backend/templates/globus-portal-framework/v2/components/getting_started_block.html
  - name: Documentation Block
    template: ../templates/documentation_block.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation_block.html
  - name: Documentation Page
    template: ../templates/documentation.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation.html
  - name: Documentation Overview
    template: ../templates/documentation/overview.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation/overview.html
  - name: Documentation on Transfers
    template: ../templates/documentation/transfers.html
    destination: /backend/templates/globus-portal-framework/v2/components/documentation/overview.html
  - name: Global Stylesheet
    template: ../templates/style.css
    destination: /backend/static/
  - name: Illustration
    template: ../templates/identity/illustration.svg
    destination: /backend/static/
  - name: Customization Block Template
    template: ../templates/customization.html
    destination: /backend/templates/globus-portal-framework/v2/components/ 

static: 
  - name: Primary Logo File
    template: ../templates/identity/ESnet_Logo.png
    destination: /backend/static/
  - name: Secondary Logo File
    template: ../templates/identity/ESnet_Logo_Sphere.svg
    destination: /backend/static/
  - name: Transfer Page Image
    template: ../templates/identity/Transfer_Page.png
    destination: /backend/static/  
  - name: Berkeley Lab Footer Badge
    template: ../templates/identity/LBNL_Logo.png
    destination: /backend/static/ 
  - name: Transfer Page Image
    template: ../templates/identity/DOE_Logo.png
    destination: /backend/static/ 
  - name: Logo File
    template: ../templates/identity/file.png
    destination: /backend/static/
  - name: Logo File
    template: ../templates/identity/folder.png
    destination: /backend/static/  




