---
- name: Read in Variable Values from settings.yml
  include_vars:
    file: ../../settings.yml
    name: settings

- name: Ensure Directories Exist
  file:
    path: "{{ item.destination | dirname }}"
    state: directory
  with_items: "{{ settings.templates }}"

- name: Install Templates
  copy:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
  with_items: "{{ settings.templates }}"